//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyCompany("CN=SGI Ltd.")]
[assembly: AssemblyProduct("SGI Retail Customization")]
[assembly: AssemblyCopyright("Copyright © 2022")]
[assembly: AssemblyVersion("10.0.1192.76")]
[assembly: AssemblyFileVersion("10.26.22183.2")]

// Generated by the MSBuild WriteCodeFragment class.

