// <auto-generated />
namespace CDC.Commerce.RetailProxy.CardReader
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.Dynamics.Commerce.RetailProxy;
    
    /// <summary>
    /// Class implements Store Operations Manager.
    /// </summary>
    [GeneratedCodeAttribute("CDC.Commerce.RetailProxy.CardReader", "1.0")]
    internal class StoreOperationsManager : IStoreOperationsManager
    {
        private IContext context;

        /// <summary>
        /// Initializes a new instance of the <see cref="StoreOperationsManager"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public StoreOperationsManager(IContext context)
        {
            this.context = context;
        }
    
        
        /// <summary>
        /// AuthenticateCard method.
        /// </summary>
        /// <param name="cnicNumber">The cnicNumber.</param>
        /// <param name="cardNumber">The cardNumber.</param>
        /// <returns>bool object.</returns>
        public async Task<bool> AuthenticateCard(string cnicNumber, string cardNumber)
        {       
            return await this.context.ExecuteOperationSingleResultAsync<bool>(
                "",
                "StoreOperations",
                "AuthenticateCard",
                true, null, OperationParameter.Create("cnicNumber", cnicNumber, false),
                  OperationParameter.Create("cardNumber", cardNumber, false));
        }
        
    }
    
 }
