// <auto-generated />
namespace CDC.Commerce.RetailProxy.FractionalSale
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using Microsoft.Dynamics.Commerce.RetailProxy;
    using Microsoft.Dynamics.Commerce.RetailProxy.Adapters;
    using Microsoft.OData.Client;
    
    /// <summary>
    /// ProductInformation entity class.
    /// </summary>
    
    [GeneratedCodeAttribute("CDC.Commerce.RetailProxy.FractionalSale", "1.0")]
    public class ProductInformation : CommerceEntity
    { 
        /// 
        /// Initializes a new instance of the <see cref="ProductInformation" /> class.
        /// 
        public ProductInformation()
        {
            
        }
      
        /// <summary>
        /// Gets or sets the RetailStoreId.
        /// </summary>
        public string RetailStoreId
        {
            get
            {
                return this.retailStoreId;
            }
        
            set
            {
                this.retailStoreId = value;
                this.OnPropertyChanged("RetailStoreId");
            }
        }
      
        private string retailStoreId;
      
        /// <summary>
        /// Gets or sets the ProductId.
        /// </summary>
        public long ProductId
        {
            get
            {
                return this.productId;
            }
        
            set
            {
                this.productId = value;
                this.OnPropertyChanged("ProductId");
            }
        }
      
        private long productId;
      
        /// <summary>
        /// Gets or sets the UnitOfMeasure.
        /// </summary>
        public string UnitOfMeasure
        {
            get
            {
                return this.unitOfMeasure;
            }
        
            set
            {
                this.unitOfMeasure = value;
                this.OnPropertyChanged("UnitOfMeasure");
            }
        }
      
        private string unitOfMeasure;
      
    }
    
}
  